DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS ITEM_ATTRIBUTE;

CREATE TABLE ITEM (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  type VARCHAR(50) NOT NULL,
  weapon INT DEFAULT NULL,
  armor INT DEFAULT NULL,
  constlevel INT NOT NULL,
  mainpath VARCHAR(5) NOT NULL,
  mainlevel VARCHAR(5) NOT NULL,
  secondarypath VARCHAR(5) DEFAULT NULL,
  secondarylevel VARCHAR(5) DEFAULT NULL
);

CREATE TABLE ITEM_ATTRIBUTE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_id INT NOT NULL,
  key VARCHAR(250) DEFAULT NULL,
  value VARCHAR(250) DEFAULT NULL,
  FOREIGN KEY (item_id) REFERENCES ITEM(id)
);

CREATE TABLE WEAPON (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_id INT NOT NULL,
  key VARCHAR(250) DEFAULT NULL,
  value VARCHAR(250) DEFAULT NULL
);